### PR TITLE
Use notifications, add directory support

### PR DESCRIPTION
**Pull request by zdykstra**
Haiku has neat native notification support, so lets take advantage of it. The following actions now generate a notification:

* Starting an upload
* Finishing an upload
* Network offline

If possible, the UploadIt icon is used instead of the default Tracker icon. 

Additionally, use 'zip' when a directory is detected. This writes stdout from zip into stdin on the curl command. Since 0x0.st strips filenames anyway, we don't bother preserving them.

Translation files have not been updated to reflect the changed strings. Please let me know how you'd like that process handled.

### CODE REVIEW

**Comment by zdykstra** [comment]
The directory-as-a-zipfile mechanism might need a bit of love. Right now, the absolute path to the directory is passed in to `zip`, and it dutifully recreates that entire structure in the archive.  There doesn't seem to be an option to `zip` to discard leading, but otherwise empty, directories.  This can be solved by invoking `sh -c " .. "` and cd'ing to the directory directly above what was passed in to `UploadIt` , then calling `zip` with a relative path to the directory.

**Comment by humdingerb** [comment]
I have to admit, I'm not sure what's meant with "sh -c"...
For a test I did this which seems to work:

```
BString command("curl -F 'file=@'\"%FILEPATH%\" http://0x0.st");
if (entry.IsDirectory()) {
	BPath parent;
	path.GetParent(&parent);
	command.Prepend("cd \"%PARENTPATH%\" && zip -qry - \"%FOLDERNAME%\" | ");
	command.ReplaceFirst("%PARENTPATH%", parent.Path());
	command.ReplaceFirst("%FOLDERNAME%", path.Leaf());
	command.ReplaceLast("%FILEPATH%", "-");
} else
	command.ReplaceFirst("%FILEPATH%", path.Path());
```

It's too bad zip is such a PITA when it comes to relative paths. There is the -j option, but with it you end up with all the files of a folder instead of the folder itself.

I also thought about allowing to process multiple files by just zipping them up before uploading. But that will fail if you have files with different paths, like from a query. One possibility may be to create a ZIP file in /temp then cd'ing to each file and adding it to the ZIP, then without path...
But I kinda feel like that distracts a bit from the simple "Upload a small file temporarily to quickly share-and-forget". Accepting a folder is as far as I want to go, I think.

Is the above code OK and would you like to amend it, or do you have a better solution in mind?

**Comment by zdykstra** [comment]
Your listed solution is largely how I did it as well, when I was testing things last night. I'll combine our two solutions and push an updated commit later today.

Is there anything you wanted me to do with the translations?

**Comment by humdingerb** [comment]
> Is there anything you wanted me to do with the translations?

You could generate new en.catkeys with "make catkeys" and add them to this PR.

**Comment by zdykstra** [comment]
I've made the changes to the directory/folder upload block and it's working as expected. A new `en.catkeys` has been generated. Please let me know if there's anything else you'd like to see changed in this PR.

**Comment by humdingerb** [comment]
All good, you just forgot to add yourself to the copyright header. :)

**Comment by zdykstra** [comment]
I'm happy to release any/all ownership of my changes to you. I can append the commit message to indicate that, if you'd prefer to have it in git history.

**Comment by humdingerb** [comment]
Nah, if you're OK with not claiming the admiration of the legions of future coders analyzing the genius code of UploadIt, be my guest. :) :) :)

**Pull request merged**
